PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE groups(id INTEGER PRIMARY KEY AUTOINCREMENT, name varchar(64), info varchar(128), pos int);
INSERT INTO "groups" VALUES(1,'Widgets','Виджеты',1);
INSERT INTO "groups" VALUES(2,'Tools','Инструменты',2);
INSERT INTO "groups" VALUES(3,'Strings','Строки',3);
INSERT INTO "groups" VALUES(4,'Arrays','Массивы',4);
INSERT INTO "groups" VALUES(5,'Network','Сеть',5);
INSERT INTO "groups" VALUES(6,'SDK','Среда',6);
INSERT INTO "groups" VALUES(7,'DataBase','Базы данных',7);
INSERT INTO "groups" VALUES(8,'Helpers','Помощники',8);
INSERT INTO "groups" VALUES(9,'','',9);
INSERT INTO "groups" VALUES(12,'Files','Файлы',10);
CREATE TABLE elements(id INTEGER PRIMARY KEY AUTOINCREMENT, name varchar(64), info varchar(64), tab int, pos int, hash varchar(32));
INSERT INTO "elements" VALUES(2,'hcTplForm','Шаблон формы',9,1,'');
INSERT INTO "elements" VALUES(3,'hcTplListBox','Список строк',1,11,'');
INSERT INTO "elements" VALUES(4,'hcTplButton','Кнопка',1,6,'');
INSERT INTO "elements" VALUES(10,'hcTplLabel','Нaдпиcь',1,7,'');
INSERT INTO "elements" VALUES(11,'hcTplEdit','Поле ввода',1,8,'');
INSERT INTO "elements" VALUES(12,'hcTplMemo','Поле ввода',1,9,'');
INSERT INTO "elements" VALUES(15,'hcTplScrollBar','Панель прокрутки',1,13,'');
INSERT INTO "elements" VALUES(17,'hcTplComboBox','Выпадающий список',1,12,'');
INSERT INTO "elements" VALUES(20,'hcTplCheckBox','Флажок',1,10,'');
INSERT INTO "elements" VALUES(22,'hcPopupMenu','Контекстное меню',9,16,'');
INSERT INTO "elements" VALUES(23,'hcHub','Разветвитель',2,23,'');
INSERT INTO "elements" VALUES(24,'hcDoData','Поток-данные',2,24,'');
INSERT INTO "elements" VALUES(25,'hcIf_else','Условный блок',2,25,'');
INSERT INTO "elements" VALUES(26,'hcFor','Цикл со счетчиком',2,26,'');
INSERT INTO "elements" VALUES(27,'hcMath','Арифметические операции +,-,*,/,... (и т.п. по списку в OpType)',2,27,'');
INSERT INTO "elements" VALUES(28,'hcConvertor','Конвертер одной величины в другую',2,29,'');
INSERT INTO "elements" VALUES(29,'hcTimer','Таймер',2,30,'');
INSERT INTO "elements" VALUES(30,'hcRandom','Случайное число',2,31,'');
INSERT INTO "elements" VALUES(31,'hcMessage','Сообщение',2,32,'');
INSERT INTO "elements" VALUES(33,'hcMemory','Память',2,34,'');
INSERT INTO "elements" VALUES(34,'hcClipboard','Буфер обмена',2,35,'');
INSERT INTO "elements" VALUES(35,'hcStrCat','Соединение двух строк в одну',3,37,'');
INSERT INTO "elements" VALUES(36,'hcStrPos','Возвращает позицию вхождения одной строки в другую',3,38,'');
INSERT INTO "elements" VALUES(37,'hcStrList','Список строк',3,39,'');
INSERT INTO "elements" VALUES(38,'hcFormatStr','Форматированная строка',3,40,'');
INSERT INTO "elements" VALUES(39,'hcCopy','Копирует часть строки',3,41,'');
INSERT INTO "elements" VALUES(40,'hcArrayRead','Чтение массива',4,43,'');
INSERT INTO "elements" VALUES(41,'hcArrayEnum','Перебор массива',4,44,'');
INSERT INTO "elements" VALUES(42,'hcHTTPText','Загрузка текста',5,46,'');
INSERT INTO "elements" VALUES(43,'hcTrace','Трассировка',9,54,'');
INSERT INTO "elements" VALUES(44,'hcCommander','Вызов команд',9,55,'');
INSERT INTO "elements" VALUES(45,'hcCommanHandler','Обработчик команд',9,58,'');
INSERT INTO "elements" VALUES(50,'hcHiAsmTrasmitter','Коммуникация со средой',6,57,'');
INSERT INTO "elements" VALUES(51,'hcSaveDialog','Сохранение файла',12,2,'');
INSERT INTO "elements" VALUES(52,'hcOpenDialog','Открытие файла',12,3,'');
INSERT INTO "elements" VALUES(53,'hcDS_SQLite','Источник данных SQLite',7,70,'');
INSERT INTO "elements" VALUES(54,'hcDSC_Exec','Запрос на выполнение',7,71,'');
INSERT INTO "elements" VALUES(55,'hcDSC_Query','Запрос данных',7,72,'');
INSERT INTO "elements" VALUES(56,'hcDSC_QueryScalar','Запрос одной ячейки',7,73,'');
INSERT INTO "elements" VALUES(57,'hcIndexToChanel','Индекс в канал',2,36,'');
INSERT INTO "elements" VALUES(58,'hcChanelToIndex','Индекс из канала',2,37,'');
INSERT INTO "elements" VALUES(59,'hcExecute','Запуск приложения',2,38,'');
INSERT INTO "elements" VALUES(60,'hcConsole','Вывод данных в консоль',2,39,'');
INSERT INTO "elements" VALUES(61,'hcTplImage','Картинка',1,17,NULL);
INSERT INTO "elements" VALUES(62,'hcMultiElement','Вложенная схема',2,40,NULL);
INSERT INTO "elements" VALUES(63,'hcFileSearch','Поиск файлов',12,1,NULL);
INSERT INTO "elements" VALUES(64,'hcTimeCounter','Счетчик времени',2,41,NULL);
INSERT INTO "elements" VALUES(65,'HubEx','Продвинутый хаб',8,2,NULL);
INSERT INTO "elements" VALUES(66,'InfoTip','Вывеска',8,1,NULL);
INSERT INTO "elements" VALUES(67,'hcStrPart','Части строки',3,42,'');
INSERT INTO "elements" VALUES(68,'hcReplace','Замена подстроки',3,43,'');
INSERT INTO "elements" VALUES(69,'hcEventFromData','Событие из данных',2,45,'');
INSERT INTO "elements" VALUES(70,'hcTplChildGroupBox','Группа элементов',1,18,NULL);
INSERT INTO "elements" VALUES(71,'hcTplGroupBox','hcTplGroupBox',9,2,NULL);
INSERT INTO "elements" VALUES(72,'hcTplDialog','Диалог',9,3,NULL);
INSERT INTO "elements" VALUES(73,'hcTplFileChooserButton','Кнопка выбора файла',1,19,NULL);
INSERT INTO "elements" VALUES(74,'hcTplColorButton','Кнопка выбора цвета',1,20,NULL);
INSERT INTO "elements" VALUES(75,'hcTplProgressBar','Панель прогресса',1,21,NULL);
INSERT INTO "elements" VALUES(76,'hcTplChildFixed','Группа фиксированных элементов',1,22,NULL);
INSERT INTO "elements" VALUES(77,'hcTplFixed','Группа фиксированных элементов',9,4,NULL);
INSERT INTO "elements" VALUES(78,'hcTplChildVBox','Вертикальная группа',1,23,NULL);
INSERT INTO "elements" VALUES(79,'hcTplVBox','Вертикальная группа',9,5,NULL);
INSERT INTO "elements" VALUES(80,'hcTplChildExpander','Расширитель',1,24,NULL);
INSERT INTO "elements" VALUES(81,'hcTplExpander','Расширитель',9,6,NULL);
INSERT INTO "elements" VALUES(82,'hcTplChildHBox','Горизонтальная группа',1,25,NULL);
INSERT INTO "elements" VALUES(83,'hcTplHBox','Горизонтальная группа',9,7,NULL);
INSERT INTO "elements" VALUES(84,'hcTplChildVButtonBox','Вертикальная группа кнопок',1,26,NULL);
INSERT INTO "elements" VALUES(85,'hcTplVButtonBox','Вертикальная группа кнопок',9,8,NULL);
INSERT INTO "elements" VALUES(86,'hcTplChildHButtonBox','Горизонтальная группа кнопок',1,27,NULL);
INSERT INTO "elements" VALUES(87,'hcTplHButtonBox','Горизонтальная группа кнопок',9,9,NULL);
INSERT INTO "elements" VALUES(88,'hcTplChildHandleBox','Съемная панель',1,28,NULL);
INSERT INTO "elements" VALUES(89,'hcTplHandleBox','Съемная панель',9,10,NULL);
INSERT INTO "elements" VALUES(90,'hcTplChildHPaned','Панель с разделителем',1,29,NULL);
INSERT INTO "elements" VALUES(91,'hcTplHPaned','Панель с разделителем',9,11,NULL);
INSERT INTO "elements" VALUES(92,'hcTplChildVPaned','Панель с разделителем',1,30,NULL);
INSERT INTO "elements" VALUES(93,'hcTplVPaned','Панель с разделителем',9,12,NULL);
INSERT INTO "elements" VALUES(94,'hcBlockFind','Поиск блоков',3,44,'');
INSERT INTO "elements" VALUES(95,'GetDataEx','Разветвлитель данных',8,3,NULL);
INSERT INTO "elements" VALUES(96,'hcInsert','Вставка строки',3,45,NULL);
INSERT INTO "elements" VALUES(97,'hcDelete','Удаление подстроки',3,46,NULL);
CREATE TABLE files(id INTEGER PRIMARY KEY AUTOINCREMENT, name varchar(128), count int);
CREATE TABLE files_link(file_id int, el_id int);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('groups',12);
INSERT INTO "sqlite_sequence" VALUES('elements',97);
COMMIT;
